language: scala
scala:
  - 2.10.4
  - 2.11.5
jdk:
  - oraclejdk7
  - openjdk6

script: sbt ++$TRAVIS_SCALA_VERSION test

notifications:
  irc:
    channels:
      - "chat.freenode.net#oncue"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
